raw=read.table("data/cv/sput.c100.h50.e0.001.log.txt2")

pdf("Figures/cv_loss.pdf", width=8, height=6)
par(mar=c(5, 4, 4, 6) + 0.1)
plot(raw$V1, raw$V2/79, type="l", col="blue", xlab="Epoch", ylab="Loss")
lines(raw$V1, raw$V3/33, col="red")
#par(new = TRUE)
#plot(raw$V1, raw$V3/33, type="l", col="red", axes=FALSE, bty="n", xlab="", ylab="")
#axis(side=4, at = pretty(range(raw$V3/33)))
#mtext("Test loss",side=4, line=4) 
legend("topright", legend=c("Training loss", "Test loss"), fill=c("blue", "red"))
dev.off()
